
CREATE TABLE customer (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    age INT NOT NULL
);

INSERT INTO customer (name, email, age) VALUES
('김민수', 'minsoo.kim@naver.com', 28),
('이영희', 'younghee.lee@gmail.com', 35),
('박준혁', 'junhyuk.park@daum.net', 22),
('최수진', 'sujin.choi@kakao.com', 30),
('정우진', 'woojin.jung@naver.com', 45),
('한지수', 'jisu.han@gmail.com', 27),
('김지훈', 'jihun.kim@daum.net', 33),
('이민영', 'minyoung.lee@kakao.com', 29),
('장서현', 'seohyun.jang@naver.com', 26),
('박다연', 'dayeon.park@gmail.com', 40),
('윤성민', 'seongmin.yoon@daum.net', 32),
('신예린', 'yerin.shin@kakao.com', 21),
('오지훈', 'jihoon.oh@naver.com', 36),
('김서준', 'seojun.kim@gmail.com', 34),
('이하은', 'haeun.lee@daum.net', 25),
('문찬영', 'chanyeong.moon@kakao.com', 31),
('임수연', 'suyeon.im@naver.com', 29),
('유진우', 'jinwoo.yoo@gmail.com', 24),
('정하영', 'hayoung.jung@daum.net', 28),
('최민준', 'minjun.choi@kakao.com', 37),
('김다현', 'dahyun.kim@naver.com', 23),
('이현우', 'hyunwoo.lee@gmail.com', 41),
('박지원', 'jiwon.park@daum.net', 27),
('정민지', 'minji.jung@kakao.com', 39),
('최지훈', 'jihoon.choi@naver.com', 30),
('이수빈', 'subin.lee@gmail.com', 35),
('강예은', 'yeeun.kang@daum.net', 28),
('김정훈', 'junghoon.kim@kakao.com', 32),
('박상현', 'sanghyun.park@naver.com', 26),
('최은정', 'eunjung.choi@gmail.com', 29),
('한성호', 'seongho.han@daum.net', 38),
('김나연', 'nayeon.kim@kakao.com', 34),
('이정우', 'jungwoo.lee@naver.com', 25),
('박세준', 'sejun.park@gmail.com', 33),
('문성은', 'sungeun.moon@daum.net', 30),
('이윤아', 'yuna.lee@kakao.com', 40),
('조한결', 'hangyeol.jo@naver.com', 22),
('정유빈', 'yubin.jung@gmail.com', 36),
('강서연', 'seoyeon.kang@daum.net', 27),
('박진호', 'jinho.park@kakao.com', 31),
('윤서하', 'seoha.yoon@naver.com', 24),
('김재민', 'jaemin.kim@gmail.com', 39),
('장우성', 'woosung.jang@daum.net', 35),
('오세영', 'seyoung.oh@kakao.com', 28),
('김예원', 'yewon.kim@naver.com', 26),
('한채영', 'chaeyoung.han@gmail.com', 32),
('이수호', 'suho.lee@daum.net', 37),
('박지현', 'jihyun.park@kakao.com', 29),
('정민수', 'minsook.jung@naver.com', 33),
('최서준', 'seojun.choi@gmail.com', 41);
